### ISSUE TITLE
donde server

### ISSUE THREAD

**Issue by coip** [skeryl/personal-site#7]
unable to locate the art! 👨‍🍳

*at least per L2 on readme.md*(can’t figure out how to quickly permalink the embedded code line on mobile)

Behavior:
![93C59008-466A-46F9-B17B-9BB1742388D9](https://user-images.githubusercontent.com/12797772/86321564-dc47c600-bbfe-11ea-8fc4-bf06193fb6c5.jpeg)

**Comment by skeryl** [comment]
accidentally stepped all over your PR and fixed this

**Comment by coip** [comment]
> accidentally stepped all over your PR and fixed this

No sweat! Glad ya got it 🤘🥳
